########################################
# Application
########################################

spring.application.name=DiamondDiary


########################################
# Database
########################################

spring.datasource.url=jdbc:postgresql://localhost:5432/diamonddiary
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
# Development only
spring.jpa.hibernate.ddl-auto=update


########################################
# API Documentation
########################################

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs


########################################
# Geocoding
########################################

geocoding.scheme=https
geocoding.host=nominatim.openstreetmap.org
geocoding.user-agent=DiamondDiary/1.0


########################################
# JWT
########################################

jwt.secret=${JWT_SECRET}
# 1 hour (milliseconds)
jwt.expiration=3600000
# Refresh token: 7 days
jwt.refresh-expiration=604800000


########################################
# Logging
########################################

logging.level.org.springframework.security=INFO